#!/usr/bin/env bash
# Script to create an RSA key pair named 'school'

# Variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair without overwriting existing keys
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE -q

# Confirm creation
if [ -f "$KEY_NAME" ]; then
    echo "RSA private key '$KEY_NAME' successfully created."
else
    echo "Failed to create RSA key."
fi
