#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and adds a custom response header

sudo apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install -y haproxy

# Enable haproxy to be started by init scripts
echo "ENABLED=1" >> /etc/default/haproxy

#edit /etc/haproxy/haproxy.cfg to add other settings
printf %s"
    frontend http-in
        bind *:80
        default_backend servers

    backend servers
        balance roundrobin
        server 6560-web-01 13.222.31.81:80 check
        server 6560-web-02 	34.204.67.32:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart haproxy to apply changes
sudo service haproxy restart