#!/usr/bin/env bash
# Installs and configures HAproxy load balancer
apt-get update -y
apt-get install -y haproxy

# Configure HAproxy
printf "global\n\tlog /dev/log local0\n\tmaxconn 2048\n\tuser haproxy\n\tgroup haproxy\n\tdaemon\n\ndefaults\n\tlog global\n\tmode http\n\toption httplog\n\toption dontlognull\n\tretries 3\n\toption redispatch\n\ttimeout connect 5000\n\ttimeout client 50000\n\ttimeout server 50000\n\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 6790-web-01 44.211.147.102:80 check\n\tserver 6790-web-02 35.174.154.227:80 check\n" > /etc/haproxy/haproxy.cfg

# Enable HAproxy init script
echo "ENABLED=1" > /etc/default/haproxy

# Restart HAproxy
service haproxy restart
