#!/usr/bin/env bash
# Installs and configures nginx web server

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create index page with Holberton School
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart nginx without systemctl
service nginx restart
