#!/usr/bin/env bash
# Configures Nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo bash -c 'cat > /etc/nginx/sites-available/default << NGINXEOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}
NGINXEOF'
service nginx restart
