#!/usr/bin/env bash
# Configures Nginx with custom 404 page
apt-get update -y
apt-get install -y nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's|server_name _;|server_name _;\n\terror_page 404 /404.html;\n\tlocation /404.html { internal; }|' /etc/nginx/sites-available/default
service nginx restart
